apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: flowise-metrics
  namespace: monitoring
spec:
  groups:
  - name: flowise
    rules:
    - record: flowise_inference_time_seconds
      expr: histogram_quantile(0.95, sum(rate(flowise_inference_duration_seconds_bucket[5m])) by (le))
    
    - record: flowise_memory_usage_bytes
      expr: sum(container_memory_usage_bytes{pod=~"flowise-.*"}) by (pod)
    
    - alert: FlowiseHighInferenceTime
      expr: flowise_inference_time_seconds > 2
      for: 5m
      labels:
        severity: warning
      annotations:
        description: "Flowise inference time is high"
        
    - alert: FlowiseHighMemoryUsage
      expr: flowise_memory_usage_bytes > 1000000000
      for: 5m
      labels:
        severity: warning
      annotations:
        description: "Flowise memory usage is high" 