apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: default
type: Opaque
data:
  database_url: BASE64_ENCODED_DATABASE_URL

---
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: default
type: Opaque
data:
  access_key: BASE64_ENCODED_AWS_ACCESS_KEY
  secret_key: BASE64_ENCODED_AWS_SECRET_KEY 